#!/usr/bin/env bash

# If a command fails, exit immediately
set -e

PIDFILE="/var/vcap/sys/run/paragon/web.pid"

/sbin/start-stop-daemon \
  --pidfile "$PIDFILE" \
  --retry TERM/20/QUIT/1/KILL \
  --oknodo \
  --stop

# Note: the --remove-pidfile option is available as of version 1.17.19 of
# start-stop-daemon, but Ubuntu stemcells only provide version 1.17.5. Thus we
# need to remove the pidfile by ourselves.
rm -f "$PIDFILE"
