#!/usr/bin/env bash

# If a command fails, exit immediately
set -e

PIDFILE="/var/vcap/sys/run/paragon/web.pid"

/sbin/start-stop-daemon \
  --pidfile "$PIDFILE" \
  --remove-pidfile \
  --retry TERM/20/QUIT/1/KILL \
  --oknodo \
  --stop