#!/usr/bin/env bash

# If a command fails, in a pipeline or not, exit immediately
set -e -o pipefail

function prepend_datetime() {
  awk -W interactive '{ system("echo -n [$(date +%FT%T%z)]"); print " " $0 }'
}

# Before redirecting stdout and stderr, copy the file descriptor for original
# stdout (file desc 1) to file descriptor number 3. That's where where BOSH is
# expecting an integer, and only that.
exec \
    3>&1 \
    1> >(prepend_datetime >> /var/vcap/sys/log/stateful-daemon/drain.stdout.log) \
    2> >(prepend_datetime >> /var/vcap/sys/log/stateful-daemon/drain.stderr.log)

output_for_bosh() {
    exit_code=$?

    if [ $exit_code -eq 0 ]; then
        echo "stateful-daemon member is properly removed from cluster"
    else
        echo "drain failed"
    fi

    echo $exit_code >&3
}

trap output_for_bosh EXIT

if echo "${BOSH_JOB_NEXT_STATE}" | grep -Fq '"persistent_disk":0'; then
    echo "detected 'scale-in' condition, decommissioning current node"
    /var/vcap/packages/stateful-daemon/bin/stateful-daemon_ctl decommission
fi
