#!/usr/bin/env bash

set -eu -o pipefail

cp -Rp "${BBR_ARTIFACT_DIRECTORY}"* /var/vcap/store/

/var/vcap/bosh/bin/monit restart all

while [[ $(/var/vcap/bosh/bin/monit summary) == *restart\ pending* ]]; do
    sleep 1
done
