#!/usr/bin/env bash

# If a command fails, exit immediately
set -e

LOG_DIR="/var/vcap/sys/log/paragon"
RUN_DIR="/var/vcap/sys/run/paragon"
PIDFILE="$RUN_DIR/web.pid"

mkdir -p "$LOG_DIR" "$RUN_DIR"

# If one of these directories is very large, chowning might take a
# very long time. Consider only chowning if dir did not yet exist
# in the previous step
chown -R vcap:vcap "$LOG_DIR" "$RUN_DIR"

# Claim $PIDFILE safely
sipid claim --pid "$$" --pid-file "$PIDFILE"

# Use `exec chpst` to run the process with reduced permissions
exec chpst -u vcap:vcap \
  /var/vcap/packages/paragon/bin/web \
  >> "$LOG_DIR/web.out.log" \
  2>> "$LOG_DIR/web.err.log"
